name = "AstroBasis"
uuid = "f9f069e8-36d3-4f22-8c0d-26ca7e8540d8"
authors = ["Mike Petersen <michael.petersen@roe.ac.uk>", "Mathieu Roule <roule@iap.fr>"]
version = "0.2.0"

[deps]
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
Memoize = "c03570c3-d221-55d1-a50c-7939bbd78826"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
julia = "1.5"
